apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhavinapp01
spec:
  selector:
    matchLabels:
      app: bhavinapp01-pod
  template:
    metadata:
      labels:
        app: bhavinapp01-pod
    spec:
      containers:
      - name: bhavinapp01-container
        image: barclaysacr02.azurecr.io/bhavinapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
